confirmOnQuit: false
disableStartupPopups: true
notARepository: "skip"
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: false
gui:
  border: single 
  # commitLength:
  #   show: true
  mouseEvents: true
  nerdFontsVersion: "3"
  scrollHeight: 4 # how many lines you scroll by
  scrollPastBottom: false # enable scrolling past the bottom
  showBottomLine: false
  showCommandLog: false
  showFileTree: true
  skipDiscardChangeWarning: true
  branchColorPatterns:
    "main": blue
  theme:
    selectedLineBgColor:
      - "#413660"
      # selectedRangeBgColor:
      #   - '#413660'
git:
  autoFetch: false
  skipHookPrefix: wip 
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
refresher:
  refreshInterval: 60
update:
  method: never
customCommands:
  - key: "#"
    description: "Push and create Merge Request"
    context: "global"
    loadingText: "Push and create Merge Request ..."
    command: git mr && glab mr view --web
